//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XMLEditor.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XMLEditor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Icon DefaultAttr {
            get {
                object obj = ResourceManager.GetObject("DefaultAttr", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon DefaultTag {
            get {
                object obj = ResourceManager.GetObject("DefaultTag", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap OpenXML {
            get {
                object obj = ResourceManager.GetObject("OpenXML", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap OpenXMLLeftPanel {
            get {
                object obj = ResourceManager.GetObject("OpenXMLLeftPanel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap OpenXMLLeftPanel1 {
            get {
                object obj = ResourceManager.GetObject("OpenXMLLeftPanel1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap OpenXMLRightPanel {
            get {
                object obj = ResourceManager.GetObject("OpenXMLRightPanel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap OpenXMLRightPanel1 {
            get {
                object obj = ResourceManager.GetObject("OpenXMLRightPanel1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap OpenXSD {
            get {
                object obj = ResourceManager.GetObject("OpenXSD", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap OpenXSL {
            get {
                object obj = ResourceManager.GetObject("OpenXSL", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap OpenXSLT {
            get {
                object obj = ResourceManager.GetObject("OpenXSLT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon vxd {
            get {
                object obj = ResourceManager.GetObject("vxd", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;!-- 
        ///  Copyright 2001 World Wide Web Consortium, (Massachusetts Institute of Technology, European Research 
        ///  Consortium for Informatics and Mathematics, Keio University). All Rights Reserved. 
        ///  http://www.w3.org/Consortium/Legal/2002/copyright-documents-20021231&quot; 
        ///  
        ///  This schema is copied from http://www.w3.org/2001/xml.xsd.
        ///--&gt;
        ///&lt;xs:schema targetNamespace=&quot;http://www.w3.org/XML/1998/namespace&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; xml:lang=&quot;en&quot;&gt;
        ///  &lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string xmlschema {
            get {
                return ResourceManager.GetString("xmlschema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&apos;1.0&apos; encoding=&apos;UTF-8&apos;?&gt;
        ///&lt;!-- 
        ///Copyright © 2001 World Wide Web Consortium, (Massachusetts Institute of 
        ///Technology, European Research Consortium for Informatics and Mathematics,
        ///Keio University). All Rights Reserved. This work is distributed under
        ///the W3C® Software License [1] .  
        /// 
        ///[1] http://www.w3.org/Consortium/Legal/2002/copyright-software-20021231
        /// 
        ///Portions © 2004-2005 Microsoft Corporation.  All rights reserved.  
        ///  This file was derived from http://www.w3.org/2001/XMLSchema. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string xsdschema {
            get {
                return ResourceManager.GetString("xsdschema", resourceCulture);
            }
        }
    }
}
